CREATE USER nmdrinkbook WITH ENCRYPTED PASSWORD 'nmdrinkbook';
CREATE DATABASE nmdrinkbook;
GRANT ALL PRIVILEGES ON DATABASE nmdrinkbook TO nmdrinkbook;

CREATE USER keycloak WITH ENCRYPTED PASSWORD 'keycloak';
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;