version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on: 
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  keycloak:
    image: wizzn/keycloak:14
    container_name: keycloak
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "28080:8080"
    volumes:
      - ./resources/keycloak/keycloak-export.json:/opt/jboss/keycloak/imports/keycloak-export.json
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=singleFile',
        '-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/keycloak-export.json',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
      ]
    restart: unless-stopped
  nm-api:
    image: norbertpal/nmdrinkbook-api
    container_name: nm-api
    ports:
      - "8000:8000"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  nm-front:
    image: norbertpal/nmdrinkbook-front
    container_name: nm-front
    ports:
      - "3000:3000"

volumes:
  pgdata: